package status

type Code = int

const (
	UNKNOW      Code = 100
	SUCCESS     Code = 200
	BAD_REQUEST Code = 400
	FAIL        Code = 400
	NOT_FOUND   Code = 404
	INTERNAL    Code = 500

	// User stauts
	USER_INVALID_PARAMS       Code = 1001
	USER_INVALID_ID           Code = 1002
	USER_NOT_FOUND            Code = 1003
	USER_MISSING_FIRST_NAME   Code = 1004
	USER_MISSING_LAST_NAME    Code = 1005
	USER_MISSING_EMAIL        Code = 1006
	USER_MISSING_PASSWORD     Code = 1013
	USER_INVALID_EMAIL        Code = 1007
	USER_EMAIL_ALREADY_EXISTS Code = 1012
	USER_MISSING_PHONE        Code = 1008
	USER_PHONE_ALREADY_EXISTS Code = 1011
	USER_INVALID_PHONE        Code = 1009
	USER_INVALID_ROLE         Code = 1019
	USER_INVALID_STATUS       Code = 1010

	// Device status
	DEVICE_INVALID_PARAMS Code = 1101
	DEVICE_MISSING_UUID   Code = 1102
	DEVICE_MISSING_NAME   Code = 1103

	// Login status
	LOGIN_MISSING_PARAMETERS Code = 1201
	LOGIN_WRONG_CREDENTIALS  Code = 1202

	// Block status
	BLOCK_MISSING_TYPE  Code = 1301
	BLOCK_MISSING_VALUE Code = 1302
	BLOCK_INVALID_TYPE  Code = 1303
)
